export const metadata = {
  title: "Terms of Service - DropPR.ai",
  description: "Terms of service and user agreements for the DropPR.ai article publishing and PR distribution platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white flex flex-col">
      <main className="flex-1 py-12 md:py-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-2">
            Terms of Service
          </h1>
          <p className="text-gray-600 mb-8 font-medium">
            Effective Date: March 4, 2026 | Version: 1.0
          </p>

          <div className="prose prose-blue max-w-none text-gray-700 leading-relaxed">
            <p className="mb-6">
              These Terms of Service ("Terms") govern your access to and use of the websites, applications,
              artificial intelligence content generation tools, media distribution services, analytics dashboards,
              and related services provided by Drop PR ("Drop PR", "we", "us", or "our") (collectively, the
              "Services").
            </p>
            <p className="mb-6">
              By creating an account, uploading content, purchasing a distribution package, or otherwise using
              the Services, you ("Customer", "User", or "you") agree to be bound by these Terms.
              If you accept these Terms on behalf of a company or other organization, you represent that you
              have authority to bind that entity.
            </p>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Definitions</h2>
              <div className="space-y-4">
                <p><strong>Content:</strong> Any video, text, images, audio, graphics, metadata, links, or other materials submitted to the Services.</p>
                <p><strong>AI Draft:</strong> An article, press release, or other written output generated by Drop PR’s artificial intelligence systems based on uploaded Content.</p>
                <p><strong>Submission or Ingestion:</strong> The successful upload of Content into Drop PR’s system for processing, AI transformation, and distribution.</p>
                <p><strong>Distribution Package:</strong> A media distribution package referencing a defined group of publisher networks or media properties available through the Services.</p>
                <p><strong>Publishers:</strong> Third-party websites, media outlets, or publishing platforms that may publish or host distributed Content.</p>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Eligibility</h2>
              <p className="mb-4">You must be at least eighteen (18) years old and legally capable of entering into contracts.</p>
              <p className="mb-2">You represent that:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>the Content you upload is lawful</li>
                <li>you have the necessary rights to distribute the Content</li>
                <li>you have authority to act on behalf of any organization you represent</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Accounts and Security</h2>
              <p className="mb-4">Users must create an account to access certain features of the Services.</p>
              <p className="mb-2">You are responsible for:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>maintaining the confidentiality of login credentials</li>
                <li>all activity conducted through your account</li>
                <li>promptly notifying Drop PR of any unauthorized access</li>
              </ul>
              <p className="mt-4 italic">Drop PR is not responsible for losses resulting from unauthorized account access caused by failure to protect credentials.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Description of Services</h2>
              <p className="mb-4">Drop PR provides an AI-powered platform that converts user-submitted video or other content into written articles or press releases and distributes those articles across participating publisher networks.</p>
              <p className="mb-2">The Services may include:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI transcription and content extraction</li>
                <li>automated article generation</li>
                <li>formatting and optimization of articles</li>
                <li>distribution across publisher networks</li>
                <li>reporting and analytics</li>
              </ul>
              <p className="mt-4">Drop PR may modify, update, or discontinue features of the Services at any time.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">5. AI-Generated Content</h2>
              <p className="mb-4">Drop PR uses artificial intelligence systems to generate written articles or press releases from uploaded Content.</p>
              <p className="mb-2">You acknowledge that:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI-generated outputs may contain errors or inaccuracies</li>
                <li>Drop PR does not verify factual accuracy</li>
                <li>you are responsible for reviewing AI-generated content before submission</li>
              </ul>
              <p className="mt-4">Drop PR does not provide editorial, legal, or factual verification services.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Publisher Network and Distribution</h2>
              <p className="mb-4">Drop PR distributes content through a network of participating publishers and media platforms. Publisher participation may change at any time due to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>editorial discretion</li>
                <li>publisher policy changes</li>
                <li>network updates</li>
                <li>technical issues or outages</li>
              </ul>
              <p className="mt-4">Drop PR does not control the editorial decisions or operational practices of publishers.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Distribution Package Fulfillment</h2>
              <p className="mb-4">Distribution packages are considered fulfilled when Content is successfully distributed to a substantial portion of the publisher network associated with the purchased package at the time of submission.</p>
              <p className="mb-2">Distribution does not guarantee:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>placement on any specific publisher</li>
                <li>permanent publication</li>
                <li>search engine indexing</li>
                <li>backlink creation</li>
                <li>traffic or engagement results</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Submission and Billing</h2>
              <p className="mb-4">Billing occurs when Content is successfully submitted into Drop PR’s system for processing and distribution. Submission is considered complete when Content is ingested by the platform.</p>
              <p className="mb-2">Package usage is calculated based on submission regardless of:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>number of publishers that ultimately publish</li>
                <li>duration of publication</li>
                <li>later removal by publishers</li>
                <li>search engine indexing</li>
                <li>traffic or engagement</li>
              </ul>
              <p className="mt-4 font-semibold">Once Content is submitted, the corresponding campaign is considered consumed and non-refundable, except where required by law.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Payments</h2>
              <p className="mb-4">Payments for Drop PR services are processed through third-party payment processors including Stripe.</p>
              <p className="mb-2">Pricing may include:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>per-campaign fees</li>
                <li>distribution packages</li>
                <li>credit bundles</li>
                <li>promotional pricing</li>
              </ul>
              <p className="mt-4">All fees are due at the time of purchase unless otherwise specified.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">10. User Content Responsibilities</h2>
              <p className="mb-4">You are solely responsible for all Content you upload. You represent and warrant that your Content:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>is accurate</li>
                <li>complies with applicable laws</li>
                <li>does not infringe intellectual property rights</li>
                <li>is not misleading or deceptive</li>
              </ul>
              <p className="mt-4 mb-2 font-semibold">Prohibited content includes:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>unlawful material</li>
                <li>defamatory statements</li>
                <li>deceptive advertising</li>
                <li>undisclosed sponsored promotions</li>
                <li>manipulative SEO schemes</li>
                <li>investment solicitations or earnings guarantees</li>
              </ul>
              <p className="mt-4">Drop PR may reject, suspend, or remove Content at its discretion.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Intellectual Property</h2>
              <p className="mb-4">Users retain ownership of the Content they upload. By submitting Content, you grant Drop PR a worldwide, non-exclusive, royalty-free license to process, reproduce, distribute, host, publish, and display the Content as necessary to provide and improve the Services.</p>
              <p className="mt-4">Publishers may edit or format distributed Content according to their editorial standards.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Copyright Complaints</h2>
              <p className="mb-4">If you believe Content distributed through the Services infringes your intellectual property rights, please submit a written notice identifying the material at issue, the alleged infringement, and your contact information.</p>
              <p className="mt-4">Drop PR may remove or disable access to disputed content.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">13. Regulatory Compliance</h2>
              <p className="mb-4">Users must comply with all applicable laws including advertising and consumer protection laws, FTC disclosure requirements, anti-spam laws, and marketing regulations. The Services may not be used for deceptive or misleading marketing practices.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">14. Suspension or Termination</h2>
              <p className="mb-4">Drop PR may suspend or terminate accounts for violation of these Terms, unlawful or harmful activity, non-payment, or security or compliance risks.</p>
              <p className="mt-4">Upon termination, previously distributed Content may remain on publisher websites outside Drop PR’s control.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">15. No Warranties</h2>
              <p className="mb-4 text-sm uppercase font-semibold">The Services are provided "as is" and "as available."</p>
              <p className="mb-2">Drop PR disclaims all warranties including merchantability, fitness for a particular purpose, and non-infringement. Drop PR does not guarantee:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>publisher placement</li>
                <li>SEO results</li>
                <li>backlinks</li>
                <li>indexing</li>
                <li>traffic or engagement</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">16. Limitation of Liability</h2>
              <p className="mb-4">To the maximum extent permitted by law, Drop PR will not be liable for any indirect, incidental, special, consequential, or punitive damages including lost profits, lost data, or business interruption.</p>
              <p className="mt-4">Drop PR’s total liability for any claim relating to the Services will not exceed the amount paid by the user to Drop PR during the six months preceding the claim.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">17. Indemnification</h2>
              <p>You agree to defend, indemnify, and hold harmless Drop PR and its affiliates, officers, directors, employees, and agents from any claims arising out of your Content, your use of the Services, violation of these Terms, or violation of applicable law.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">18. Force Majeure</h2>
              <p className="mb-4">Drop PR will not be liable for delays or failures caused by events beyond its reasonable control including internet outages, publisher network failures, data center outages, natural disasters, or acts of government.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">19. Governing Law</h2>
              <p className="mb-4">These Terms are governed by the laws of the State of Georgia, without regard to conflict of law principles. Any dispute, claim, or controversy arising out of or relating to these Terms or the Services will be resolved through binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules.</p>
              <p className="mb-4">The seat and venue of arbitration will be Atlanta, Georgia. Judgment on the arbitration award may be entered in any court of competent jurisdiction.</p>
              <p className="italic">Notwithstanding the foregoing, either party may seek temporary or injunctive relief in a court of competent jurisdiction to protect confidential information or intellectual property.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">20. Changes to Terms</h2>
              <p className="mb-4">Drop PR may update these Terms from time to time. Continued use of the Services after updates constitutes acceptance of the revised Terms.</p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">21. Contact Information</h2>
              <div className="bg-gray-50 p-6 rounded-xl border border-gray-200">
                <p className="font-bold">Drop PR</p>
                <p>AI-Powered Media & PR Distribution Platform</p>
                <p>Website: <a href="https://www.droppr.ai" className="text-blue-600 hover:underline">https://www.droppr.ai</a></p>
                <p className="mt-4">For questions regarding these Terms, please contact us through the website <a href="/contact" className="text-blue-600 hover:underline">contact page</a>.</p>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
